[project]
name = "recruitment-formatter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abhinav", email = "abhinavsharma00410@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.0",
    "pandas>=2.0.0",
    "requests>=2.31.0",
]

[project.scripts]
recruitment-formatter = "recruitment_formatter:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
